version: '3'

services:
  data-db:
    image: postgres:13
    restart: always
    container_name: udacity_capstone_postgres
    environment:
      POSTGRES_DB: udacity
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    ports:
      - 127.0.0.1:5432:5432

volumes:
  postgres-db-volume:
